version: '3'
services:
  jenkins:
    image: shiftrepo/docker-jenkins:latest
    volumes:
      # using docker in jenkins
      - /var/run/docker.sock:/var/run/docker.sock 

    ports:
      - "8080:8080"
      - "50000:50000"

